// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opnlbgdwihsebsvgbhke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbmxiZ2R3aWhzZWJzdmdiaGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NDgzNzMsImV4cCI6MjA3NjAyNDM3M30.mhlos4cHjmTdowQwilnFuuyG-8Q7Nzxi0d2Ecp9qbXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});