// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhgrfdjyzbjvhauoytlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoZ3JmZGp5emJqdmhhdW95dGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODU2MjMsImV4cCI6MjA3MzM2MTYyM30.pICPOJAKeq_dG6Mzmz0nDVT3FEdiP5m1ZURS3FQb8d0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});