// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cirgeptbfjteobxjruqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcmdlcHRiZmp0ZW9ieGpydXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3Mjk0MTUsImV4cCI6MjA3NzMwNTQxNX0.oLIHSJWj8gHXmS8Wm5A6O8SUnnlAt1MbAkNRb8Jo6RU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});